---
# tasks file for ansible_workstation

# TLP
- name: Add the TLP PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:linrunner/tlp
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install the TLP packages
  become: true
  ansible.builtin.package:
    name:
      - tlp
      - tlp-rdw
    state: latest

- name: Ensure that the TLP service is enabled
  become: true
  ansible.builtin.service:
    name: tlp
    enabled: true
    state: started

# libvirt
- name: Add the virtualization PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:jacob/virtualisation
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install the libvirt packages
  become: true
  ansible.builtin.package:
    name:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager
    state: latest

- name: Add the user to the kvm and libvirt groups
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    append: true
    groups:
      - kvm
      - libvirt

# Development Packages

- name: Add the Git Stable Releases PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add the Jonathon F's Vim PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:jonathonf/vim
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install development packages
  become: true
  ansible.builtin.package:
    name:
      - ansible
      - btrfs-progs
      - ccache
      - clang
      - cmake
      - curl
      - gdb
      - git
      - gnupg
      - lldb
      - make
      - ninja-build
      - openssh-server
      - python3
      - vim
      - xclip
      - wget
    state: latest

- name: Install development packages for Fedora
  become: true
  ansible.builtin.package:
    name:
      - clang-tools-extra
      - gcc-c++
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install development packages for Debian
  become: true
  ansible.builtin.package:
    name:
      - clang-format
      - clang-tidy
      - g++
      - python3-pip
# python-is-python3 is only on Ubuntu 20.04 and newer
#      - python-is-python3
      - zfsutils-linux
    state: latest
  when: ansible_facts['os_family'] == "Debian"

# GUI packages
- name: Install GUI system packages
  become: true
  ansible.builtin.package:
    name:
      - gnome-disk-utility
      - gnome-software
      - gnome-software-plugin-flatpak
    state: latest

# Git
- name: Create the user's Git config directory
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: ~/.config/git
    state: directory
    mode: 0770
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install the Git configuration
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: gitconfig
    dest: ~/.config/git/config
    mode: 0660
    owner: "{{ user }}"
    group: "{{ user }}"

# Flatpaks

- name: Install Flatpak
  become: true
  ansible.builtin.package:
    name: flatpak
    state: latest

- name: Add the Flathub Flatpak repository remote to the system installation
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Add the Flathub Flatpak repository remote to the user installation
  become: true
  become_user: "{{ user }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

# Install gvfs for tests?
- name: Install user Flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  with_items:
    - com.calibre_ebook.calibre
    - com.discordapp.Discord
    - com.github.geigi.cozy
    - com.github.johnfactotum.Foliate
    - com.microsoft.Teams
    - com.nextcloud.desktopclient.nextcloud
    - com.sublimemerge.App
    - com.uploadedlobster.peek
    - com.vscodium.codium
    - de.haeckerfelix.Fragments
    - im.riot.Riot
    - org.fedoraproject.MediaWriter
    - org.gnome.Books
    - org.gnome.Boxes
    - org.gnome.Builder
    - org.gnome.Calculator
    - org.gnome.Calendar
    - org.gnome.Cheese
    - org.gnome.clocks
    - org.gnome.Connections
    - org.gnome.Contacts
    - org.gnome.design.AppIconPreview
    - org.gnome.design.Palette
    - org.gnome.design.Typography
    - org.gnome.Dictionary
    - org.gnome.Epiphany
    - org.gnome.Evince
    - org.gnome.Extensions
    - org.gnome.Firmware
    - org.gnome.font-viewer
    - org.gnome.Fractal
    - org.gnome.Geary
    - org.gnome.gedit
    - org.gnome.GHex
    - org.gnome.gitlab.somas.Apostrophe
    - org.gnome.Logs
    - org.gnome.Lollypop
    - org.gnome.Maps
    - org.gnome.Notes
    - org.gnome.PasswordSafe
    - org.gnome.Photos
    - org.gnome.Podcasts
    - org.gnome.PowerStats
    - org.gnome.seahorse.Application
    - org.gnome.Todo
    - org.gnome.Totem
    - org.gnome.Weather
    - org.keepassxc.KeePassXC
    - org.libreoffice.LibreOffice
    - org.linux_hardware.hw-probe

# - name: Install system Flatpak applications
#   community.general.flatpak:
#     name: org.linux_hardware.hw-probe
#     state: present
#     method: system

- name: Alias the VSCodium Flatpak as 'codium'
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: codium.fish
    dest: "{{ u.home }}/.config/fish/functions/codium.fish"
    mode: 0660
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Alias the Sublime Merge Flatpak as 'smerge'
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: smerge.fish
    dest: "{{ u.home }}/.config/fish/functions/smerge.fish"
    mode: 0660
    owner: "{{ user }}"
    group: "{{ user }}"

# Settings

- name: Install dependencies for dconf
  become: true
  ansible.builtin.package:
    name:
      - dbus
      - dconf-cli
      - dconf-gsettings-backend
      - dconf-service
      - python3-psutil
    state: latest

- name: Blank screen after 12 minutes of inactivity
  community.general.dconf:
    key: /org/gnome/desktop/session/idle-delay
    value: "uint32 900"
    state: present

- name: Automatically lock the screen after one hour
  community.general.dconf:
    key: /org/gnome/desktop/screensaver/lock-delay
    value: "uint32 3600"
    state: present

- name: Automatically delete trash content
  community.general.dconf:
    key: /org/gnome/desktop/privacy/remove-old-trash-files
    value: "true"
    state: present

- name: Automatically delete temporary files
  community.general.dconf:
    key: /org/gnome/desktop/privacy/remove-old-temp-files
    value: "true"
    state: present

- name: Automatically delete trashed files after 14 days
  community.general.dconf:
    key: /org/gnome/desktop/privacy/old-files-age
    value: "uint32 14"
    state: present

- name: Automatically send technical reports
  community.general.dconf:
    key: /org/gnome/desktop/privacy/report-technical-problems
    value: "true"
    state: present

- name: Send software usage statistics
  community.general.dconf:
    key: /org/gnome/desktop/privacy/send-software-usage-stats
    value: "true"
    state: present

- name: Enable location services
  community.general.dconf:
    key: /org/gnome/system/location/enabled
    value: "true"
    state: present

- name: Enable automatic time zone detection
  community.general.dconf:
    key: /org/gnome/desktop/datetime/automatic-timezone
    value: "true"
    state: present

- name: Enable Night Light
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"
    state: present

# Podman
- name: Add the Kubic repository key
  become: true
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_20.04/Release.key
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Enable the Kubic repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /
  when: ansible_facts['os_family'] == "Debian"

- name: Install Podman
  become: true
  ansible.builtin.package:
    name:
      - crun
      - podman
      - fuse-overlayfs
    state: latest

- name: Create the system's Podman config directory
  become: true
  ansible.builtin.file:
    path: /etc/containers
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install the system storage config file for Podman
  become: true
  ansible.builtin.copy:
    src: system-storage.conf
    dest: /etc/containers/storage.conf
    mode: 0644
    owner: root
    group: root

- name: Create the user's Podman config directory
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: ~/.config/containers
    state: directory
    mode: 0770
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install the user storage config file for Podman
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: user-storage.conf
    dest: ~/.config/containers/storage.conf
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Ensure that the Podman auto-update service is enabled for root containers
  become: true
  ansible.builtin.service:
    name: podman-auto-update
    enabled: true
    state: started

- name: Ensure that the Podman auto-update service is enabled for rootless containers
  become: true
  ansible.builtin.systemd:
    name: podman-auto-update.service
    enabled: true
    state: started
    scope: global
