---
- name: Converge
  hosts: all
  tasks:
    - name: Update the Aptitude's package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"
    - name: Include ansible_workstation
      include_role:
        name: "ansible_workstation"
